[package]
name = "xmas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-map = "2.7.3"
enum-map-derive = "0.17.0"
rstest = "0.23.0"
thiserror = "1.0.64"
