[workspace]
members = [
    "create_new_day",
    "template",
    "xmas",
    "day_01",
    "day_02",
    "day_03",
    "day_04",
    "day_05",
    "day_06",
    "day_07",
    "day_08",
]
resolver = "2"
